---
- name: Realizacion del reto1
  hosts: test
  become: true
  
  
    tasks:

    - name: Collect only kernel facts
      ansible.builtin.setup:
        filter:
        - '*kernel'
      register: setup

    - debug:
        var: setup
  
  
