---
- name: Realizacion del reto1
  hosts: windows
  become: true
  gather_facts: no
  
  
  tasks:
    - name: Gather facts from Chocolatey
      chocolatey.chocolatey.win_chocolatey_facts:

    - name: Displays the gathered facts
      ansible.builtin.debug:
        var: ansible_chocolatey
  
  
  
   # - name: Check windows version
   #     ansible.windows.win_command: windows --version
   #   register: check_windows_version
      
   # - ansible.builtin.debug:
   #     msg: Windows Version is {{ check_windows_version.stdout_lines[0] }} 

   # - name: Obtener el hostname de la máquina e imprimir 
   #   ansible.builtin.setup:
   #     filter:
   #     - 'ansible_hostname'
   #   register: setup

   # - debug:
   #     var: setup
  
  
