---
- name: Realizacion del reto1
  hosts: test
  become: true
  gather_facts: no
  
  
  tasks:

    - name: Collect only kernel facts
      ansible.builtin.setup:
        filter:
        - 'ansible_hostname'
      register: setup

    - debug:
        var: setup
  
  
