---
- name: Realizacion del reto1
  hosts: all
  become: yes
  gather_facts: false
  
  tasks:
    - name: Hostanme
      win_command: ver
      register: windows_version

    - name: Imprimir la versión de Windows en pantalla
      debug:
        msg: "La versión de Windows es {{ windows_version.stdout_lines[0] }}"
  
  
  
  
 
   
   
   
  
  
