---
- name: Realizacion del reto1
  hosts: windows
  become: true
  gather_facts: no
  
  
  tasks:

   # - name: Obtener el hostname de la máquina e imprimir 
   #   ansible.builtin.setup:
   #     filter:
   #     - 'ansible_hostname'
   #   register: setup

   # - debug:
   #     var: setup
  
  
