---
- name: Realizacion del reto1
  hosts: all
  #become: yes
 
  gather_facts: false
  
  
  tasks:
    - name: Gather facts from Chocolatey
      chocolatey.chocolatey.win_chocolatey_facts:

    - name: Displays the gathered facts
      ansible.builtin.debug:
        var: ansible_chocolatey

  
  
  #  - name: install iis
  #    win_feature:
  #      name: Web-Server
  #      state: present

  #  - name: start iis service
  #    win_service:
  #      name: W3Svc
  #      state: started
        
        
    #- name: Enable firewall
    #  community.windows.win_firewall:
    #  state: enabled
  
  
  
  
  
  

   # - name: Obtener el hostname de la máquina e imprimir 
   #   ansible.builtin.setup:
   #     filter:
   #     - 'ansible_hostname'
   #   register: setup

   # - debug:
   #     var: setup
   
   
   
  
  
